spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:V-PostgreSQL01.indukern.local}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:mdlp}
    username: ${POSTGRES_USER_NAME:postgres}
    password: ${POSTGRES_PASSWORD:I7895321i}
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: 'true'
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: 'true'
        format_sql: 'true'
    show-sql: 'false'
    hibernate:
      ddl-auto: update

#???????? ?????????? ?? ?????????, ${ENV_KEY:defaultValueExample}